name: dart_libdogecoin
description: Dart bindings for libdogecoin
version: 0.1.0+1
homepage: https://github.com/alamshafil/dart-libdogecoin

environment:
  sdk: '>=2.15.1 <3.0.0'

# dependencies:

dev_dependencies:
  ffigen: 
  lints: 
  test: 
dependencies: 
  ffi: 

ffigen:
  output: 'lib/libdogecoin_bindings.dart'
  headers:
    entry-points:
      - 'dogecoin/**.h'
  name: 'libdogecoin'
  description: 'Bindings to libdogecoin'
