name: dart_libdogecoin
description: Dart bindings for libdogecoin
version: 0.1.2
homepage: https://github.com/alamshafil/dart-libdogecoin

environment:
  sdk: ">=3.0.0 <4.0.0"

# dependencies:

dev_dependencies:
  ffigen: 
  lints: 
  test: 
dependencies: 
  ffi: 

ffigen:
  output: 'lib/dart_libdogecoin_raw.dart'
  headers:
    entry-points:
      - 'include/**.h'
  name: 'libdogecoin'
  description: 'Bindings to libdogecoin'
